# Generated by Django 5.1.7 on 2025-04-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='matricule',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
