# Generated by Django 5.1.7 on 2025-04-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_validuser_alter_info_matricule_alter_info_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidUser',
        ),
    ]
