# Generated by Django 5.1.7 on 2025-05-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_validuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50)),
                ('txtfile', models.FileField(blank=True, null=True, upload_to='txtfiles/', verbose_name='ECG File')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
