# Generated by Django 5.1.7 on 2025-05-14 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
