# Generated by Django 5.1.7 on 2025-05-15 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ecgsignal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecgsignal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userdb'),
        ),
    ]
