# Generated by Django 5.1.7 on 2025-05-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_ecgsignal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECGRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg_file', models.FileField(upload_to='ecg_files/')),
                ('session_number', models.IntegerField(default=1)),
                ('record_number', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userdb')),
            ],
        ),
        migrations.DeleteModel(
            name='ECGSignal',
        ),
    ]
