# Generated by Django 5.1.7 on 2025-05-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SVMModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('fichier_svm', models.FileField(upload_to='svm/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userdb',
            options={'managed': False, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
