# Generated by Django 5.1.7 on 2025-05-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_svmmodels_alter_userdb_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svmmodels',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
