# Generated by Django 5.1.7 on 2025-05-28 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_svmmodels_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='svmmodels',
            name='ecg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.ecgrecord'),
        ),
    ]
